

#' @title Add Caption to Tracker
#'
#' @param tracker
#' @param caption \code{character} or \code{grob} to add to footer. Text can be
#' \code{html} or \code{md} and is passed directly to \link[gridtext]{richtext_grob}
#' @param position data.frame generated by get \link[ggtrack]{get_positions}
#'
#' @importFrom gridtext richtext_grob
#' @importFrom ggplot2 annotation_custom
#'
#' @return
#' @export
#'
#' @examples
add_caption <- function(tracker, caption, position) {

  if (is.character(caption)) {
    tg <- richtext_grob(caption, x = 0, hjust = 0, name = 'caption')
  } else if ('grob' %in% class(caption)) {
    tg <- caption
  } else {
    stop('A caption needs to be either text or a "grob"')
  }

  # define position
  p <- as.list(position[position$order == 'C', ])

  tracker +
    annotation_custom(tg, xmin = p$xmin, xmax = p$xmax, )

}
