

#' @title Add Logo to Tracker
#'
#' @param tracker
#' @param logo
#' @param height_tracker
#' @param position data.frame generated by get \link[ggtrack]{get_positions}
#'
#' @importFrom tools file_ext
#' @import RCurl
#' @import png
#' @import jpeg
#'
#' @return
#' @export
#'
#' @examples
add_logo <- function(tracker, logo, height_tracker, position) {

  # check if url or file
  typ <- ifelse(grepl('http', logo), 'url', 'file')

  # check type of logo
  ext <- tolower(file_ext(logo))

  if (typ == 'url') {
    logo <- RCurl::getURLContent(logo)
  }

  if (ext == 'png') {
    logo_imported <- png::readPNG(logo)
  } else if (ext %in% c('jpg', 'jpeg')) {
    logo_imported <- jpeg::readJPEG(logo)
  } else {
    stop(paste0('Unable to Add filetype: ', ext))
  }

  lg <- grid::rasterGrob(logo_imported, x = 1, just = 'right', height = unit(height_tracker, 'cm'), name = 'logo')

  # define position
  p <- as.list(position[position$order == 'L', ])

  tracker +
    annotation_custom(lg, xmin = p$xmin, xmax = p$xmax)

}
