

#' @title Add QR Code to Tracker
#'
#' @param tracker
#' @param qr_content \code{character} content passed to \link[qrencoder]{qrencode}. A time stamp is automatically added plus the current
#' git commit where available.
#' @param color
#' @param height_tracker
#' @param position data.frame generated by get \link[ggtrack]{get_positions}
#' @param justification numeric between 0 and 1 passed to \link[grid]{rasterGrob}.
#'
#' @import qrencoder
#' @return
#' @export
#'
#' @examples
add_qr <- function(tracker, qr_content, color, height_tracker, position, justification) {

  # setup QR code
  qr_matrix <- make_qr(qr_content, color)

  qr <- grid::rasterGrob(qr_matrix, interpolate = FALSE, x = justification, just = justification, height = unit(height_tracker, 'cm'), name = 'qrcode')

  # define position
  p <- as.list(position[position$order == 'Q', ])

  tracker +
    annotation_custom(qr, xmin = p$xmin, xmax = p$xmax)

}


#' @title Make QR
#'
#' @param qr_content \code{character} content passed to \link[qrencoder]{qrencode}. A time stamp is automatically added plus the current
#' git commit where available.
#' @param color
#' @param color_bg
#'
#' @return
#'
#' @examples
make_qr <- function(qr_content, color = 'black', color_bg = 'white') {

  g <- Sys.which('git')

  if (as.character(g) == '') {
    git <- 'noGit'
  } else {
    git <- strtrim(system("git rev-parse HEAD", intern=TRUE), 7)
  }


  qr_matrix <- qrencoder::qrencode(paste(qr_content,
                                         git,
                                         format(Sys.time(), '%Y%m%d-%H%M%S')))

  qr_matrix[qr_matrix == 1] <- color
  qr_matrix[qr_matrix == 0] <- color_bg

  return(qr_matrix)
}
















